markdown: rdiscount
permalink: /:title/
url: http://xlcxyn.github.io/
name: xlcxyn.github.io
author: xlcxyn
qq: 34046923
email: xlcxyn@gmail.com
duoshuo: //
cnzz: //
weibo: //
github: xlcxyn
pygments: true
safe: true
paginate: 30
about: "这里是 xlcxyn 的个人Blog，创建于 2016 年， Jekyll @ GitHub。<br /><br />这里包含了部分个人的“折腾”过程、结论、随手记和成果，切换到分类模可以更快地找到感兴趣的内容。本人记性不好，难免遗忘，故作此记录..."
